= Spring Boot Notes

== When SpringBoot starts

	1. Check Auto-registered @PropertySources - 17 of them.
	2. Check the META-INF/spring.factories - look for auto-configurations and check their conditionals
	3. Check @Conditionals
	4. Classpath scanning and loadig Bean/Component/Configuration objects, other stereotpes extending Component (and from 2.2, loads ConfigurationProperties)

== Property Sources

A Property Source can be any one standard ones that Spring Boot looks up, in an order of precedence. The lowest numbered ones are overridden by the highe numbered ones.

For a full reference, check out the https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config[Spring Reference to External Configuration]

. Default properties (specified by setting SpringApplication.setDefaultProperties).
. @PropertySource annotations on your @Configuration classes. Please note that such property sources are not added to the Environment until the application context is being refreshed. This is too late to configure certain properties such as logging.* and spring.main.* which are read before refresh begins.
. Config data (such as application.properties files)
. A RandomValuePropertySource that has properties only in random.*.
. OS environment variables.
. Java System properties (System.getProperties()).
. JNDI attributes from java:comp/env.
. ServletContext init parameters.
. ServletConfig init parameters.
. Properties from SPRING_APPLICATION_JSON (inline JSON embedded in an environment variable or system property).
. Command line arguments.
. properties attribute on your tests. Available on @SpringBootTest and the test annotations for testing a particular slice of your application.
. @TestPropertySource annotations on your tests.
. Devtools global settings properties in the $HOME/.config/spring-boot directory when devtools is active.
. Application properties packaged inside your jar (application.properties and YAML variants).
. Profile-specific application properties packaged inside your jar (application-{profile}.properties and YAML variants).
. Application properties outside of your packaged jar (application.properties and YAML variants).
. Profile-specific application properties outside of your packaged jar (application-{profile}.properties and YAML variants).

== ConfigurationProperties

`ConfigurationProperties` allow for defining a new hierarchy of configurations that share a common prefix. These are best used for custom property loading. Some interesting rules apply:

For a camelCase property `preferredGreeting` defined in a ConfigurationProperties class defined with prefix `xyz`: +

	@ConfigurationProperties(prefix="xyz")
	public class CustomProperties {
		private String preferredGreeting;
	}

  Spring has a set of relaxed-binding rules. These include the following possible definitions where configured:
  preferredGreeting
  preferred-greeting
  preferred_greeting
  preferredgreeting
  PREFERRED_GREETING

** Properties Files:: allow camel case, kebab case, or underscore notation - uses standard list syntax using [ ] or comma-separated values
** YAML Files:: allow camel case, kebab case, or underscore notation - uses standard YAML list syntax or comma-separated values
** Environment Variables:: allow upper case format with underscore as the delimiter. _ should not be used within a property name - uses numeric values surrounded by underscores, such as XYZ_NICKNAME_1_OTHER = xyz.nickName[1].other
** System properties:: allow camel case, kebab case, or underscore notation - uses standard list syntax using [ ] or comma-separated values


Should you declare a `@ConfigurationProperties`, unless you specify `@SpringBootApplication`, you should specify a `@EnableConfigurationProperties`. A prime example of where this is useful, is in the `@SpringBootTest(classes=CustomProperties.class)`, which, is not auto-annotated with `@EnableConfigurationProperties`. The `@Value` annotation that reads a specific value from a property source, is somewhat different since it does not actually need field injection as is produced by using `@ConfigurationPrperties`.

ConfigurationProperties require mutators to set values. In order to achieve immutability, a `@ConstructorBinding` can be used (either on the class if there is only one constructor, and on a constructor if there are more than one). An `@EnableConfigurationProperties` is most-likely required when using `@ConstructorBinding`, since beans created using `@Component` or `@Bean` and those using `@Import` will not know how to bind. 


== AutoConfiguration

AutoConfiguration is simply a @Configuration which is listed in the META-INF/spring.factories. Per the reference guide, AutoConfigurations should never be a target of component scanning and should *only* be loaded from the spring.factories. For dependent AutoConfigurations, use the `@AutoConfigureAfter` or `@AutoConfigureBefore` annotations at the Configuration's class. There is an additional `@AutoConfigureOrder` that can be used.

=== Testing

Testing AutoConfigurations require the use of an `ApplicationContextRunner` which provides a static builder `withConfiguration(AutoConfiguratoins.of(...))`. To read in more detail, visit the https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-test-autoconfig[Testing Spring Boot Auto Configurations].

=== Conditionals
* `@ConditionalOnBean(DataSource.class)`: The condition is true only if the user specified a DataSource @Bean in a @Configuration.
* `@ConditionalOnClass(DataSource.class)`: The condition is true if the DataSource class is on the classpath.
* `@ConditionalOnCloudPlatform(CloudPlatform.Heroku)`: The condition is true if the CloudPlatform is set to Heroku.
* `@ConditionalOnExpression("someSpELExpression)`: The condition is true if the SpEL expression is true.
* `@ConditionalOnJava(JavaVersion.EIGHT)`: The condition is true if the current Java version is 8.
* `@ConditionalOnJndi("java:comp/env/ejb/myEJB")`: The condition is true if the specified JNDI context exists.
* `@ConditionalOnMissingBean(DataSource.class)`: The condition is true if the user did not specify a DataSource @Bean in any @Configuration.
* `@ConditionalOnMissingClass(DataSource.class)`: The condition is true if the DataSource class is not on the classpath.
* `@ConditionalOnNotWebApplication`: The condition is true if the application is not a web application.
* `@ConditionalOnProperty("my.property")`: The condition is true if my.property is set.
* `@ConditionalOnResource("classpath:my.properties")`: The condition is true if my.properties exists.
* `@ConditionalOnSingleCandidate(DataSource.class)`: Matches if there is exactly one primary DataSource bean specified in your application.
* `@ConditionalOnWebApplication`: The condition is true if the application is a web application.

